button_fusion: !!python/object:classes.line.Area
  max_x: 2234
  max_y: 503
  min_x: 1840
  min_y: 450
stats:
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 720
    min_x: 2190
    min_y: 640
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 720
    min_x: 1570
    min_y: 640
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 720
    min_x: 1460
    min_y: 640
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 720
    min_x: 1379
    min_y: 640
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 720
    min_x: 2050
    min_y: 640
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 720
    min_x: 2300
    min_y: 640
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 720
    min_x: 2400
    min_y: 640
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 800
    min_x: 2190
    min_y: 720
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 800
    min_x: 1570
    min_y: 720
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 800
    min_x: 1460
    min_y: 720
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 800
    min_x: 1379
    min_y: 720
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 800
    min_x: 2050
    min_y: 720
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 800
    min_x: 2300
    min_y: 720
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 800
    min_x: 2400
    min_y: 720
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 880
    min_x: 2190
    min_y: 800
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 880
    min_x: 1570
    min_y: 800
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 880
    min_x: 1460
    min_y: 800
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 880
    min_x: 1379
    min_y: 800
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 880
    min_x: 2050
    min_y: 800
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 880
    min_x: 2300
    min_y: 800
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 880
    min_x: 2400
    min_y: 800
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 960
    min_x: 2190
    min_y: 880
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 960
    min_x: 1570
    min_y: 880
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 960
    min_x: 1460
    min_y: 880
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 960
    min_x: 1379
    min_y: 880
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 960
    min_x: 2050
    min_y: 880
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 960
    min_x: 2300
    min_y: 880
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 960
    min_x: 2400
    min_y: 880
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1040
    min_x: 2190
    min_y: 960
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1040
    min_x: 1570
    min_y: 960
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1040
    min_x: 1460
    min_y: 960
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1040
    min_x: 1379
    min_y: 960
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1040
    min_x: 2050
    min_y: 960
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1040
    min_x: 2300
    min_y: 960
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1040
    min_x: 2400
    min_y: 960
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1120
    min_x: 2190
    min_y: 1040
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1120
    min_x: 1570
    min_y: 1040
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1120
    min_x: 1460
    min_y: 1040
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1120
    min_x: 1379
    min_y: 1040
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1120
    min_x: 2050
    min_y: 1040
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1120
    min_x: 2300
    min_y: 1040
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1120
    min_x: 2400
    min_y: 1040
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1200
    min_x: 2190
    min_y: 1120
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1200
    min_x: 1570
    min_y: 1120
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1200
    min_x: 1460
    min_y: 1120
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1200
    min_x: 1379
    min_y: 1120
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1200
    min_x: 2050
    min_y: 1120
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1200
    min_x: 2300
    min_y: 1120
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1200
    min_x: 2400
    min_y: 1120
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1280
    min_x: 2190
    min_y: 1200
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1280
    min_x: 1570
    min_y: 1200
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1280
    min_x: 1460
    min_y: 1200
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1280
    min_x: 1379
    min_y: 1200
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1280
    min_x: 2050
    min_y: 1200
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1280
    min_x: 2300
    min_y: 1200
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1280
    min_x: 2400
    min_y: 1200
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1360
    min_x: 2190
    min_y: 1280
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1360
    min_x: 1570
    min_y: 1280
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1360
    min_x: 1460
    min_y: 1280
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1360
    min_x: 1379
    min_y: 1280
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1360
    min_x: 2050
    min_y: 1280
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1360
    min_x: 2300
    min_y: 1280
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1360
    min_x: 2400
    min_y: 1280
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1440
    min_x: 2190
    min_y: 1360
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1440
    min_x: 1570
    min_y: 1360
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1440
    min_x: 1460
    min_y: 1360
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1440
    min_x: 1379
    min_y: 1360
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1440
    min_x: 2050
    min_y: 1360
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1440
    min_x: 2300
    min_y: 1360
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1440
    min_x: 2400
    min_y: 1360
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1520
    min_x: 2190
    min_y: 1440
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1520
    min_x: 1570
    min_y: 1440
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1520
    min_x: 1460
    min_y: 1440
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1520
    min_x: 1379
    min_y: 1440
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1520
    min_x: 2050
    min_y: 1440
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1520
    min_x: 2300
    min_y: 1440
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1520
    min_x: 2400
    min_y: 1440
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1600
    min_x: 2190
    min_y: 1520
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1600
    min_x: 1570
    min_y: 1520
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1600
    min_x: 1460
    min_y: 1520
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1600
    min_x: 1379
    min_y: 1520
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1600
    min_x: 2050
    min_y: 1520
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1600
    min_x: 2300
    min_y: 1520
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1600
    min_x: 2400
    min_y: 1520
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1680
    min_x: 2190
    min_y: 1600
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1680
    min_x: 1570
    min_y: 1600
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1680
    min_x: 1460
    min_y: 1600
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1680
    min_x: 1379
    min_y: 1600
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1680
    min_x: 2050
    min_y: 1600
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1680
    min_x: 2300
    min_y: 1600
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1680
    min_x: 2400
    min_y: 1600
- !!python/object:classes.line.Line
  base: !!python/object:classes.line.Area
    max_x: 2300
    max_y: 1760
    min_x: 2190
    min_y: 1680
  effect: !!python/object:classes.line.Area
    max_x: 2050
    max_y: 1760
    min_x: 1570
    min_y: 1680
  maximum: !!python/object:classes.line.Area
    max_x: 1570
    max_y: 1760
    min_x: 1460
    min_y: 1680
  minimum: !!python/object:classes.line.Area
    max_x: 1460
    max_y: 1760
    min_x: 1379
    min_y: 1680
  modify: !!python/object:classes.line.Area
    max_x: 2190
    max_y: 1760
    min_x: 2050
    min_y: 1680
  pa: !!python/object:classes.line.Area
    max_x: 2400
    max_y: 1760
    min_x: 2300
    min_y: 1680
  ra: !!python/object:classes.line.Area
    max_x: 2500
    max_y: 1760
    min_x: 2400
    min_y: 1680
